GameGuessNumberBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: GameGuessNumberBundle:Default:index }

login:
    pattern:  /login
    defaults: { _controller: GameGuessNumberBundle:Main:index }
    
main:
    pattern:  /main/{name}
    defaults: { _controller: GameGuessNumberBundle:Main:main }