GameGuessNumberBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: GameGuessNumberBundle:Default:index }

login:
    pattern:  /login
    defaults: { _controller: GameGuessNumberBundle:Main:login }
    
index:
    pattern:  /index
    defaults: { _controller: GameGuessNumberBundle:Main:index }
    
save:
    pattern:  /save/{name}/{score}/{type}
    defaults: { _controller: GameGuessNumberBundle:Main:save}
    
show:
    pattern:  /show/{gtype}
    defaults: { _controller: GameGuessNumberBundle:Main:show}
     
help:
    pattern:  /help
    defaults: { _controller: GameGuessNumberBundle:Main:help}