AcmeTaskBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeTaskBundle:Default:index }

task_new:
    pattern:  /new
    defaults: { _controller: AcmeTaskBundle:Default:new }