parameters:
#    sepa_blog.example.class: Sepa\BlogBundle\Example

services:
#    sepa_blog.example:
#        class: %sepa_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
